spring:
  application:
    name: yyc_client
 
server:
  port: 1001
feign:
  hystrix:
     enabled: true
eureka:
  client:
   serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port} # 指定此实例的ip
    #prefer-ip-address: true # 注册时使用ip而不是主机名
  #server:
    #enable-self-preservation: false # 开启保护机制
